name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: $6cc239e3874554011dd0423131875f491eed303244c9e73ea3c1757379e83c6006-ed4cdb2f-4501-4038-9b74-74579c9fc77b00f0328013eef30f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                # Use "/" if your index.html is in the root
          app_build_command: "echo Skipping build"  # <== Add this line to force skip
